// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* blackjack.h
   Generated by wsdl2h 2.8.132 from blackjack.wsdl and typemap.dat
   2026-05-29 18:49:25 GMT

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE.

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/**

@page page_notes Notes

@note HINTS:
 - Run soapcpp2 on blackjack.h to generate the SOAP/XML processing logic:
   Use soapcpp2 -I to specify paths for #import
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Edit 'typemap.dat' to control namespace bindings and type mappings:
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -c to generate pure C code.
 - Use wsdl2h -R to include the REST operations defined by the WSDLs.
 - Use wsdl2h -O3 or -O4 to optimize by removing unused schema components.
 - Use wsdl2h -d to enable DOM support for xsd:any and xsd:anyType.
 - Use wsdl2h -F to simulate struct-type derivation in C (also works in C++).
 - Use wsdl2h -f to generate flat C++ class hierarchy, removes type derivation.
 - Use wsdl2h -g to generate top-level root elements with readers and writers.
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Use wsdl2h -L to remove this @note and all other @note comments.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE GENERATED soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://ejemplo.com/blackjack.wsdl                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER typemap variable:                                               *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

#include <vector>
template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * $SIZE typemap variable:                                                    *
 *   int                                                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to 'typemap.dat' then rerun wsdl2h (use wsdl2h -t typemap.dat):

ns1 = "http://ejemplo.com/blackjack.wsdl"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://ejemplo.com/blackjack.wsdl"
//gsoap ns1   schema namespace:	http://ejemplo.com/blackjack.wsdl
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


class _ns1__PedirCarta;

class _ns1__PedirCartaResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://ejemplo.com/blackjack.wsdl                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://ejemplo.com/blackjack.wsdl                                        *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://ejemplo.com/blackjack.wsdl":PedirCarta
/// @brief "http://ejemplo.com/blackjack.wsdl":PedirCarta is a complexType.
///
/// @note class _ns1__PedirCarta operations:
/// - _ns1__PedirCarta* soap_new__ns1__PedirCarta(soap*) allocate and default initialize
/// - _ns1__PedirCarta* soap_new__ns1__PedirCarta(soap*, int num) allocate and default initialize an array
/// - _ns1__PedirCarta* soap_new_req__ns1__PedirCarta(soap*, ...) allocate, set required members
/// - _ns1__PedirCarta* soap_new_set__ns1__PedirCarta(soap*, ...) allocate, set all public members
/// - _ns1__PedirCarta::soap_default(soap*) default initialize members
/// - int soap_read__ns1__PedirCarta(soap*, _ns1__PedirCarta*) deserialize from a stream
/// - int soap_write__ns1__PedirCarta(soap*, _ns1__PedirCarta*) serialize to a stream
/// - _ns1__PedirCarta* _ns1__PedirCarta::soap_dup(soap*) returns deep copy of _ns1__PedirCarta, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__PedirCarta::soap_del() deep deletes _ns1__PedirCarta data members, use only after _ns1__PedirCarta::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__PedirCarta::soap_type() returns SOAP_TYPE__ns1__PedirCarta or derived type identifier
class _ns1__PedirCarta
{ public:
/// Element "id_partida" of type xs:int.
    int                                  id_USCOREpartida               1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "http://ejemplo.com/blackjack.wsdl":PedirCartaResponse
/// @brief "http://ejemplo.com/blackjack.wsdl":PedirCartaResponse is a complexType.
///
/// @note class _ns1__PedirCartaResponse operations:
/// - _ns1__PedirCartaResponse* soap_new__ns1__PedirCartaResponse(soap*) allocate and default initialize
/// - _ns1__PedirCartaResponse* soap_new__ns1__PedirCartaResponse(soap*, int num) allocate and default initialize an array
/// - _ns1__PedirCartaResponse* soap_new_req__ns1__PedirCartaResponse(soap*, ...) allocate, set required members
/// - _ns1__PedirCartaResponse* soap_new_set__ns1__PedirCartaResponse(soap*, ...) allocate, set all public members
/// - _ns1__PedirCartaResponse::soap_default(soap*) default initialize members
/// - int soap_read__ns1__PedirCartaResponse(soap*, _ns1__PedirCartaResponse*) deserialize from a stream
/// - int soap_write__ns1__PedirCartaResponse(soap*, _ns1__PedirCartaResponse*) serialize to a stream
/// - _ns1__PedirCartaResponse* _ns1__PedirCartaResponse::soap_dup(soap*) returns deep copy of _ns1__PedirCartaResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__PedirCartaResponse::soap_del() deep deletes _ns1__PedirCartaResponse data members, use only after _ns1__PedirCartaResponse::soap_dup(NULL) (use soapcpp2 -Ed)
/// - int _ns1__PedirCartaResponse::soap_type() returns SOAP_TYPE__ns1__PedirCartaResponse or derived type identifier
class _ns1__PedirCartaResponse
{ public:
/// Element "nueva_carta" of type xs:string.
    std::string                          nueva_USCOREcarta              1;	///< Required element.
/// Pointer to soap context that manages this instance.
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://ejemplo.com/blackjack.wsdl                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://ejemplo.com/blackjack.wsdl                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	BlackjackBinding 
//gsoap ns1  service type:	BlackjackPortType 
//gsoap ns1  service port:	http://127.0.0.1:8080 
//gsoap ns1  service namespace:	http://ejemplo.com/blackjack.wsdl 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Blackjack Definitions

@section Blackjack_bindings Service Bindings

  - @ref BlackjackBinding

@section Blackjack_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/** @page BlackjackBinding Binding "BlackjackBinding"

@section BlackjackBinding_operations Operations of Binding "BlackjackBinding"

  - @ref __ns1__PedirCarta

@section BlackjackBinding_ports Default endpoints of Binding "BlackjackBinding"

  - http://127.0.0.1:8080

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   BlackjackBinding                                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__PedirCarta                                                        *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__PedirCarta" of service binding "BlackjackBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://127.0.0.1:8080

  - Default SOAP action or REST location path:
    - "http://ejemplo.com/PedirCarta"

  - Addressing input action: "http://ejemplo.com/PedirCarta"

  - Addressing output action: "http://ejemplo.com/PedirCartaResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__PedirCarta(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__PedirCarta*                   ns1__PedirCarta,
    // output parameters:
    _ns1__PedirCartaResponse           &ns1__PedirCartaResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__PedirCarta(
    struct soap *soap,
    // input parameters:
    _ns1__PedirCarta*                   ns1__PedirCarta,
    // output parameters:
    _ns1__PedirCartaResponse           &ns1__PedirCartaResponse
  );
@endcode

C++ proxy class (defined in soapBlackjackBindingProxy.h generated with soapcpp2):
@code
  class BlackjackBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapBlackjackBindingService.h generated with soapcpp2):
@code
  class BlackjackBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	PedirCarta SOAP
//gsoap ns1  service method-style:	PedirCarta document
//gsoap ns1  service method-encoding:	PedirCarta literal
//gsoap ns1  service method-input-action:	PedirCarta http://ejemplo.com/PedirCarta
//gsoap ns1  service method-output-action:	PedirCarta http://ejemplo.com/PedirCartaResponse
int __ns1__PedirCarta(
    _ns1__PedirCarta*                   ns1__PedirCarta,	///< Input parameter
    _ns1__PedirCartaResponse           &ns1__PedirCartaResponse	///< Output parameter
);

/** @page BlackjackBinding Binding "BlackjackBinding"

@section BlackjackBinding_policy_enablers Policy Enablers of Binding "BlackjackBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/** @page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings that are contractually bound by WSDLs and
are auto-generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data
bindings are adopted from XML schemas as part of the WSDL types section or when
running wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

@note The following readers and writers are C/C++ data type (de)serializers
auto-generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

@note Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

@note Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

@note The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_set_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_set_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


*/

/**

@section ns1 Top-level root elements of schema "http://ejemplo.com/blackjack.wsdl"

  - <ns1:PedirCarta> @ref _ns1__PedirCarta
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__PedirCarta(struct soap*, _ns1__PedirCarta*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__PedirCarta(struct soap*, _ns1__PedirCarta*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__PedirCarta(struct soap*, const char *URL, _ns1__PedirCarta*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__PedirCarta(struct soap*, const char *URL, _ns1__PedirCarta*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__PedirCarta(struct soap*, const char *URL, _ns1__PedirCarta*);
    soap_POST_recv__ns1__PedirCarta(struct soap*, _ns1__PedirCarta*);
    @endcode

  - <ns1:PedirCartaResponse> @ref _ns1__PedirCartaResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__PedirCartaResponse(struct soap*, _ns1__PedirCartaResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__PedirCartaResponse(struct soap*, _ns1__PedirCartaResponse*);
    // REST GET (returns SOAP_OK on success):
    soap_GET__ns1__PedirCartaResponse(struct soap*, const char *URL, _ns1__PedirCartaResponse*);
    // REST PUT (returns SOAP_OK on success):
    soap_PUT__ns1__PedirCartaResponse(struct soap*, const char *URL, _ns1__PedirCartaResponse*);
    // REST POST (returns SOAP_OK on success):
    soap_POST_send__ns1__PedirCartaResponse(struct soap*, const char *URL, _ns1__PedirCartaResponse*);
    soap_POST_recv__ns1__PedirCartaResponse(struct soap*, _ns1__PedirCartaResponse*);
    @endcode

*/

/* End of blackjack.h */
