/* soapBlackjackBindingProxy.h
   Generated by gSOAP 2.8.132 for blackjack.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBlackjackBindingProxy_H
#define soapBlackjackBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC BlackjackBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'BlackjackBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in blackjack.h, if any
        /// Construct a proxy with new managing context
        BlackjackBindingProxy();
        /// Copy constructor
        BlackjackBindingProxy(const BlackjackBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        BlackjackBindingProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        BlackjackBindingProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        BlackjackBindingProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        BlackjackBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BlackjackBindingProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BlackjackBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~BlackjackBindingProxy();
        /// Initializer used by constructors
        virtual void BlackjackBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BlackjackBindingProxy *copy();
        /// Copy assignment
        BlackjackBindingProxy& operator=(const BlackjackBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'PedirCarta' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int PedirCarta(_ns1__PedirCarta *ns1__PedirCarta, _ns1__PedirCartaResponse &ns1__PedirCartaResponse) { return this->PedirCarta(NULL, NULL, ns1__PedirCarta, ns1__PedirCartaResponse); }
        /// Web service synchronous operation 'PedirCarta' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int PedirCarta(const char *soap_endpoint_url, const char *soap_action, _ns1__PedirCarta *ns1__PedirCarta, _ns1__PedirCartaResponse &ns1__PedirCartaResponse) { return this->send_PedirCarta(soap_endpoint_url, soap_action, ns1__PedirCarta) || this->recv_PedirCarta(ns1__PedirCartaResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_PedirCarta' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_PedirCarta(const char *soap_endpoint_url, const char *soap_action, _ns1__PedirCarta *ns1__PedirCarta);
        /// Web service asynchronous operation 'recv_PedirCarta' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_PedirCarta(_ns1__PedirCartaResponse &ns1__PedirCartaResponse);
    };
#endif
