/* soapBlackjackBindingProxy.cpp
   Generated by gSOAP 2.8.132 for blackjack.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapBlackjackBindingProxy.h"

BlackjackBindingProxy::BlackjackBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	BlackjackBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BlackjackBindingProxy::BlackjackBindingProxy(const BlackjackBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

BlackjackBindingProxy::BlackjackBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	BlackjackBindingProxy_init(_soap->imode, _soap->omode);
}

BlackjackBindingProxy::BlackjackBindingProxy(struct soap *_soap, const char *soap_endpoint_url)
{	this->soap = _soap;
	this->soap_own = false;
	BlackjackBindingProxy_init(_soap->imode, _soap->omode);
	soap_endpoint = soap_endpoint_url;
}

BlackjackBindingProxy::BlackjackBindingProxy(const char *soap_endpoint_url)
{	this->soap = soap_new();
	this->soap_own = true;
	BlackjackBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

BlackjackBindingProxy::BlackjackBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	BlackjackBindingProxy_init(iomode, iomode);
}

BlackjackBindingProxy::BlackjackBindingProxy(const char *soap_endpoint_url, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	BlackjackBindingProxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

BlackjackBindingProxy::BlackjackBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	BlackjackBindingProxy_init(imode, omode);
}

BlackjackBindingProxy::~BlackjackBindingProxy()
{	if (this->soap_own)
	{	BlackjackBindingProxy::destroy();
		soap_free(this->soap);
	}
}

void BlackjackBindingProxy::BlackjackBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL },
        { "SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "ns1", "http://ejemplo.com/blackjack.wsdl", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this->soap, namespaces);
}

BlackjackBindingProxy *BlackjackBindingProxy::copy()
{	BlackjackBindingProxy *dup = SOAP_NEW_UNMANAGED(BlackjackBindingProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

BlackjackBindingProxy& BlackjackBindingProxy::operator=(const BlackjackBindingProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void BlackjackBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void BlackjackBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	BlackjackBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void BlackjackBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *BlackjackBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *BlackjackBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *BlackjackBindingProxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this->soap);
}

const char *BlackjackBindingProxy::soap_fault_string()
{	return ::soap_fault_string(this->soap);
}

const char *BlackjackBindingProxy::soap_fault_detail()
{	return ::soap_fault_detail(this->soap);
}

int BlackjackBindingProxy::soap_close_socket()
{	return ::soap_closesock(this->soap);
}

int BlackjackBindingProxy::soap_force_close_socket()
{	return ::soap_force_closesock(this->soap);
}

void BlackjackBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BlackjackBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *BlackjackBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int BlackjackBindingProxy::send_PedirCarta(const char *soap_endpoint_url, const char *soap_action, _ns1__PedirCarta *ns1__PedirCarta)
{
	struct __ns1__PedirCarta soap_tmp___ns1__PedirCarta;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://127.0.0.1:8080";
	if (soap_action == NULL)
		soap_action = "http://ejemplo.com/PedirCarta";
	soap_tmp___ns1__PedirCarta.ns1__PedirCarta = ns1__PedirCarta;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__PedirCarta(soap, &soap_tmp___ns1__PedirCarta);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PedirCarta(soap, &soap_tmp___ns1__PedirCarta, "-ns1:PedirCarta", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PedirCarta(soap, &soap_tmp___ns1__PedirCarta, "-ns1:PedirCarta", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int BlackjackBindingProxy::recv_PedirCarta(_ns1__PedirCartaResponse &ns1__PedirCartaResponse)
{
	ns1__PedirCartaResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PedirCartaResponse.soap_get(soap, "ns1:PedirCartaResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
