/* soapProxy.h
   Generated by gSOAP 2.8.132 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapProxy_H
#define soapProxy_H
#include "soapH.h"

    class SOAP_CMAC Proxy : public soap {
      public:
        /// Endpoint URL of service 'Proxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in service.h, if any
        /// Construct a proxy with new managing context
        Proxy();
        /// Copy constructor
        Proxy(const Proxy& rhs);
        /// Construct proxy given a managing context
        Proxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        Proxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        Proxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        Proxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        Proxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        Proxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~Proxy();
        /// Initializer used by constructors
        virtual void Proxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual Proxy *copy();
        /// Copy assignment
        Proxy& operator=(const Proxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'HacerAlgo' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int HacerAlgo(char *parametro, int &resultado) { return this->HacerAlgo(NULL, NULL, parametro, resultado); }
        /// Web service synchronous operation 'HacerAlgo' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int HacerAlgo(const char *soap_endpoint_url, const char *soap_action, char *parametro, int &resultado) { return this->send_HacerAlgo(soap_endpoint_url, soap_action, parametro) || this->recv_HacerAlgo(resultado) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_HacerAlgo' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_HacerAlgo(const char *soap_endpoint_url, const char *soap_action, char *parametro);
        /// Web service asynchronous operation 'recv_HacerAlgo' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_HacerAlgo(int &resultado);
    };
#endif
