/* soapProxy.cpp
   Generated by gSOAP 2.8.132 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapProxy.h"

Proxy::Proxy() : soap(SOAP_IO_DEFAULT)
{	Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

Proxy::Proxy(const Proxy& rhs)
{	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
}

Proxy::Proxy(const struct soap &_soap) : soap(_soap)
{ }

Proxy::Proxy(const struct soap &_soap, const char *soap_endpoint_url) : soap(_soap)
{
	soap_endpoint = soap_endpoint_url;
}

Proxy::Proxy(const char *soap_endpoint_url) : soap(SOAP_IO_DEFAULT)
{	Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = soap_endpoint_url;
}

Proxy::Proxy(soap_mode iomode) : soap(iomode)
{	Proxy_init(iomode, iomode);
}

Proxy::Proxy(const char *soap_endpoint_url, soap_mode iomode) : soap(iomode)
{	Proxy_init(iomode, iomode);
	soap_endpoint = soap_endpoint_url;
}

Proxy::Proxy(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	Proxy_init(imode, omode);
}

Proxy::~Proxy()
{
	Proxy::destroy();
}

void Proxy::Proxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL },
        { "SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "ns1", "http://tempuri.org/ns1.xsd", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this, namespaces);
}

Proxy *Proxy::copy()
{	Proxy *dup = SOAP_NEW_UNMANAGED(Proxy(*(struct soap*)this));
	return dup;
}

Proxy& Proxy::operator=(const Proxy& rhs)
{	soap_done(this);
	soap_copy_context(this, &rhs);
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void Proxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void Proxy::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	Proxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void Proxy::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *Proxy::soap_header()
{	return this->header;
}

::SOAP_ENV__Fault *Proxy::soap_fault()
{	return this->fault;
}

const char *Proxy::soap_fault_subcode()
{	return ::soap_fault_subcode(this);
}

const char *Proxy::soap_fault_string()
{	return ::soap_fault_string(this);
}

const char *Proxy::soap_fault_detail()
{	return ::soap_fault_detail(this);
}

int Proxy::soap_close_socket()
{	return ::soap_closesock(this);
}

int Proxy::soap_force_close_socket()
{	return ::soap_force_closesock(this);
}

void Proxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void Proxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *Proxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int Proxy::send_HacerAlgo(const char *soap_endpoint_url, const char *soap_action, char *parametro)
{
	struct soap *soap = this;
	struct ns1__HacerAlgo soap_tmp_ns1__HacerAlgo;
	if (soap_endpoint_url != NULL)
		soap_endpoint = soap_endpoint_url;
	soap_tmp_ns1__HacerAlgo.parametro = parametro;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__HacerAlgo(soap, &soap_tmp_ns1__HacerAlgo);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__HacerAlgo(soap, &soap_tmp_ns1__HacerAlgo, "ns1:HacerAlgo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__HacerAlgo(soap, &soap_tmp_ns1__HacerAlgo, "ns1:HacerAlgo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

int Proxy::recv_HacerAlgo(int &resultado)
{
	struct soap *soap = this;
	struct ns1__HacerAlgoResponse *soap_tmp_ns1__HacerAlgoResponse;
	soap_default_int(soap, &resultado);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ns1__HacerAlgoResponse = soap_get_ns1__HacerAlgoResponse(soap, NULL, "ns1:HacerAlgoResponse", NULL);
	if (!soap_tmp_ns1__HacerAlgoResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	resultado = soap_tmp_ns1__HacerAlgoResponse->resultado;
	return soap_closesock(soap);
}
/* End of client proxy code */
