/* soapService.cpp
   Generated by gSOAP 2.8.132 for service.h

gSOAP XML Web services tools
Copyright (C) 2000-2023, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapService.h"

Service::Service() : soap(SOAP_IO_DEFAULT)
{	Service_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

Service::Service(const Service& rhs)
{	soap_copy_context(this, &rhs);
}

Service::Service(const struct soap &_soap) : soap(_soap)
{ }

Service::Service(soap_mode iomode) : soap(iomode)
{	Service_init(iomode, iomode);
}

Service::Service(soap_mode imode, soap_mode omode) : soap(imode, omode)
{	Service_init(imode, omode);
}

Service::~Service()
{
	Service::destroy();
}

void Service::Service_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] = {
        { "SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL },
        { "SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL },
        { "xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL },
        { "xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL },
        { "ns1", "http://tempuri.org/ns1.xsd", NULL, NULL },
        { NULL, NULL, NULL, NULL} /* end of namespaces[] */
    };
	soap_set_namespaces(this, namespaces);
}

void Service::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void Service::reset()
{	this->destroy();
	soap_done(this);
	soap_initialize(this);
	Service_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
Service *Service::copy()
{	Service *dup = SOAP_NEW_UNMANAGED(Service(*(struct soap*)this));
	return dup;
}
#endif

Service& Service::operator=(const Service& rhs)
{	soap_done(this);
	soap_copy_context(this, &rhs);
	return *this;
}

int Service::soap_close_socket()
{	return soap_closesock(this);
}

int Service::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int Service::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int Service::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int Service::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int Service::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void Service::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void Service::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *Service::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void Service::soap_noheader()
{	this->header = NULL;
}

::SOAP_ENV__Header *Service::soap_header()
{	return this->header;
}

#ifndef WITH_NOIO
int Service::run(int port, int backlog)
{	if (!soap_valid_socket(this->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->errnum == 0) // timeout?
				this->error = SOAP_OK;
			break;
		}
		if (this->serve())
			break;
		this->destroy();
	}
	return this->error;
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int Service::ssl_run(int port, int backlog)
{	if (!soap_valid_socket(this->master) && !soap_valid_socket(this->bind(NULL, port, backlog)))
		return this->error;
	for (;;)
	{	if (!soap_valid_socket(this->accept()))
		{	if (this->errnum == 0) // timeout?
				this->error = SOAP_OK;
			break;
		}
		if (this->ssl_accept() || this->serve())
			break;
		this->destroy();
	}
	return this->error;
}
#endif

SOAP_SOCKET Service::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET Service::accept()
{	return soap_accept(this);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int Service::ssl_accept()
{	return soap_ssl_accept(this);
}
#endif
#endif

int Service::serve()
{
#ifndef WITH_FASTCGI
	this->keep_alive = this->max_keep_alive + 1;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (this->keep_alive > 0 && this->max_keep_alive > 0)
			this->keep_alive--;
#endif
		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if ((dispatch() || (this->fserveloop && this->fserveloop(this))) && this->error && this->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns1__HacerAlgo(Service*);

int Service::dispatch()
{
	(void)soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:HacerAlgo"))
		return serve_ns1__HacerAlgo(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns1__HacerAlgo(Service *soap)
{	struct ns1__HacerAlgo soap_tmp_ns1__HacerAlgo;
	struct ns1__HacerAlgoResponse soap_tmp_ns1__HacerAlgoResponse;
	soap_default_ns1__HacerAlgoResponse(soap, &soap_tmp_ns1__HacerAlgoResponse);
	soap_default_ns1__HacerAlgo(soap, &soap_tmp_ns1__HacerAlgo);
	if (!soap_get_ns1__HacerAlgo(soap, &soap_tmp_ns1__HacerAlgo, "ns1:HacerAlgo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->HacerAlgo(soap_tmp_ns1__HacerAlgo.parametro, soap_tmp_ns1__HacerAlgoResponse.resultado);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize_ns1__HacerAlgoResponse(soap, &soap_tmp_ns1__HacerAlgoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__HacerAlgoResponse(soap, &soap_tmp_ns1__HacerAlgoResponse, "ns1:HacerAlgoResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__HacerAlgoResponse(soap, &soap_tmp_ns1__HacerAlgoResponse, "ns1:HacerAlgoResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
